default:
  @just --list

test: test-python test-c test-cpp test-rust

test-python:
  python eval/evaluate.py --data_path=trees/data/ --dir_path=trees/python/

test-c:
  eval/evaluate.c.sh trees/data trees/c

test-cpp:
  eval/evaluate.cpp.sh trees/data trees/cpp

test-rust:
  eval/evaluate.rust.sh trees/data trees/rust
