name: "Leetcode Rust Tests"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/leetcode/**/rust"
      - "src/leetcode/bin/evaluate.rush.sh"
      - ".github/workflows/leetcode-rust-tests.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/leetcode/**/rust"
      - "src/leetcode/bin/evaluate.rust.sh"
      - ".github/workflows/leetcode-rust-tests.yml"
  release:
    types: [created]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - run: sudo snap install --edge --classic just

      - name: cache cargo
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Leetcode Rust Tests
        run: cd src/leetcode/ && just test-rust
