name: "Leetcode Prolog Tests"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/leetcode/**/prolog"
      - "src/leetcode/eval/evaluate.pro.sh"
      - ".github/workflows/leetcode-prolog-tests.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/leetcode/**/prolog"
      - "src/leetcode/eval/evaluate.pro.sh"
      - ".github/workflows/leetcode-prolog-tests.yml"
  release:
    types: [created]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - run: sudo snap install --edge --classic just

      - name: Run Leetcode Prolog Tests
        run: cd src/leetcode/ && just test-prolog
