name: "memalloc lib checks"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/memalloc.yml"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/memalloc.yml"
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: "check arena.c"
        run: cd src/memalloc/arena && make
