name: "papersai tests"

on:
  push:
    branches: [main]
    paths:
      - "src/papersai/**"
  pull_request:
    branches: [main]
    paths:
      - "src/papersai/**"
  release:
    types: [created]
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          cache-dependency-glob: |
            **/src/papersai/pyproject.toml

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: src/papersai/
        run: uv sync --all-extras

      - name: Ruff
        working-directory: src/papersai/
        run: |
          uv run ruff check papersai

      - name: Test with PyTest
        working-directory: src/papersai/
        run: |
          uv run pytest -v .
